apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: retail-store
spec:
  selector:
    app: checkout          
    environment: dev
    componet: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080