apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: retail-store
spec:
  type: NodePort
  selector:
    app: ui          
    environment: dev
    componet: frontend
  ports:
  - name: ui-service-port
    protocol: TCP
    port: 8080 
    targetPort: 8080
    nodePort: 30080