apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalog-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: catalog
      component: backend
  namespaceSelector:
    matchNames:
      - retail-store-{{ .Values.global.environment }}
  endpoints:
  - port: catalog
    path: /metrics
    interval: 15s
