apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-configmap
  namespace: retail-store
data:
  # Postgresql
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: postgres
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: postgresql:5432
  RETAIL_ORDERS_PERSISTENCE_NAME: postgres
  RETAIL_ORDERS_PERSISTENCE_USERNAME: postgres_user
  # Rabbitmq
  RETAIL_ORDERS_MESSAGING_PROVIDER: rabbitmq
  # RETAIL_ORDERS_MESSAGING_SQS_TOPIC: orders-events
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: rabbitmq:5672
  RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME: rabbitmq_user