apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders  
  labels:
    app: orders              
    environment: {{ .Values.environment }}
spec:           
  # replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: orders         
      component: backend
  template:
    metadata:
      labels:
        app: orders         
        component: backend
    spec:
      containers:
      - name: orders
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080   
        envFrom:
        - configMapRef:
            name: orders-configmap
        - secretRef:
            name: orders-secret
        resources:
{{ toYaml .Values.resources | indent 10 }}