apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
  namespace: retail-store
type: Opaque
data:
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: cGFzc3dvcmQ=
  RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD: cGFzc3dvcmQ=