apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment    
  labels:
    app: cart              
    environment: {{ .Values.environment }}
spec: 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cart            
      component: backend
  template:
    metadata:
      labels:
        app: cart          
        component: backend
    spec:
      containers:
      - name: cart
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080   
        envFrom:
        - configMapRef:
            name: cart-configmap
        - secretRef:
            name: secrets-basic-auth
        resources:
{{ toYaml .Values.resources | indent 10 }}