{{- if eq .Values.aws.authMethod "static" }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-static-creds
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.secretAccessKey }}
{{- end }}
