apiVersion: v1
kind: Service
metadata:
  name: cart # if i give anyother name like cart-service ui will call http://cart-service:8080 not http://cart:8080
  namespace: retail-store
spec:
  selector:
    app: cart          
    environment: dev
    component: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 