apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-configmap
data:
  # Postgresql
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: redis
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: redis://redis:6379
  RETAIL_CHECKOUT_ENDPOINTS_ORDERS: http://orders:8080
  RETAIL_CHECKOUT_SHIPPING_NAME_PREFIX: checkout_complete