{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
spec:
  selector: 
    tier: db
  ports:
  - name: dynamodb-port
    protocol: TCP
    port: 8000
    targetPort: 8000
{{- end }}