# latestelopment specific overrides
retail-store-cart:
  enabled: true
  image:
    tag: latest # Use latest-specific image tags
  replicaCount: 1 # Lower replica count for latestelopment
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi

retail-store-catalog:
  enabled: true
  image:
    tag: latest
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi

retail-store-checkout:
  enabled: true
  image:
    tag: v1
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi

retail-store-orders:
  enabled: true
  image:
    tag: latest
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi

retail-store-ui:
  enabled: true
  image:
    tag: latest
  replicaCount: 1 
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi