# latestelopment specific overrides
retail-store-cart:
  enabled: true
  image:
    tag: latest # Use latest-specific image tags
  replicaCount: 1 # Lower replica count for latestelopment
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

retail-store-catalog:
  enabled: true
  image:
    tag: latest
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

retail-store-checkout:
  enabled: true
  image:
    tag: v1
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi # Higher memory for Node.js backends to avoid OOM
    limits:
      cpu: 400m
      memory: 512Mi

retail-store-orders:
  enabled: true
  image:
    tag: latest
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

retail-store-ui:
  enabled: true
  image:
    tag: latest
  replicaCount: 1 
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi