# Default values for all services
retail-store-cart:
  enabled: true
  replicaCount: 1

retail-store-catalog:
  enabled: true
  replicaCount: 1

retail-store-checkout:
  enabled: true
  replicaCount: 1

retail-store-orders:
  enabled: true
  replicaCount: 1

retail-store-ui:
  enabled: true
  replicaCount: 1

# Database defaults
retail-store-mysql:
  enabled: true
retail-store-redis:
  enabled: true
retail-store-rabbitmq:
  enabled: true
retail-store-postgresql:
  enabled: true
retail-store-dynamodb:
  enabled: true