# Production specific overrides
retail-store-cart:
  image:
    tag: v1
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

retail-store-catalog:
  image:
    tag: v1
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

retail-store-checkout:
  image:
    tag: v1
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

retail-store-orders:
  image:
    tag: v1
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

retail-store-ui:
  image:
    tag: v1
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi