cart:
  environment: prod
  image:
    tag: v2
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

catalog:
  environment: prod
  image:
    tag: v2
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

checkout:
  environment: prod
  image:
    tag: v2
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

orders:
  environment: prod
  image:
    tag: v2
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

ui:
  environment: prod
  image:
    tag: v2
  replicaCount: 2
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

# helm upgrade --install retail-store . -n retail-store-prod -f values.yaml -f values-prod.yaml

# this means all other services like orders ui checkout will deploy normally define in thier own values.yaml
# but for checkout its replicaCount will be changed to 2 and in cart its resources will be changed to given in values-prod.yaml