apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ui
      component: backend
  namespaceSelector:
    matchNames:
      - retail-store-dev
  endpoints:
  - port: ui
    path: /actuator/prometheus
    interval: 15s
