apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ui          
    component: frontend
  ports:
  - name: ui-service-port
    protocol: TCP
    port: 8080 
    targetPort: 8080
    {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}