apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
    component: backend # if i give anyother name like orders-service ui will call http://orders-service:8080 not http://orders:8080
spec:
  selector:
    app: orders         
    component: backend
  ports:
  - protocol: TCP
    name: orders
    port: 8080
    targetPort: 8080 