apiVersion: v1
kind: Service
metadata:
  name: cart # if i give anyother name like cart-service ui will call http://cart-service:8080 not http://cart:8080
spec:
  selector:
    app: cart         
    component: backend
  ports:
  - protocol: TCP
    name: cart
    port: 8080
    targetPort: 8080 