# Global ENV
environment: dev

# CART SERVICE
retail-store-cart:
  image:
    tag: v1 # Use dev-specific image tags
  aws:
    authMethod: static
  configmap:
    endpoint: http://dynamodb:8000
  secrets:
    enabled: true
    accessKeyId: local
    secretAccessKey: local
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi

# CATALOG SERVICE  
retail-store-catalog:
  image:
    tag: v1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi

# CHECKOUT SERVICE
retail-store-checkout:
  image:
    tag: v1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi

# ORDERS SERVICE
retail-store-orders:
  image:
    tag: v1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi

# UI SERVICE
retail-store-ui:
  image:
    tag: v1 
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m 
      memory: 512Mi
  Service:
    type: NodePort
    nodePort: 30080

# MYSQL DATABASE
retail-store-mysql:
  enabled: true
  replicaCount: 1
  persistence:
    storageClass: local-path
    size: 5Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  secrets:
    rootPassword: password
    userPassword: password

# POSTGRESQL DATABASE
retail-store-postgresql:
  enabled: true
  replicaCount: 1
  persistence:
    storageClass: local-path
    size: 5Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi